### PR TITLE
drag cursor

### PR DESCRIPTION
**Pull request by Mazedotexe**
wow thank you mazedotexe this is a very useful fork i can even have a different cursor on one singular part, wowie

# Changes
**Describe what your changes/additions are and what they do:**
i made a singular style change for the better, theres really no reason not to accept this ._.

### CODE REVIEW

**Comment by 05Konz** [comment]
use the react gui instead 🗿

**Comment by Mazedotexe** [comment]
> use the react gui instead 🗿

What’s the difference, really?

**Comment by 05Konz** [comment]
> > use the react gui instead 🗿
> 
> What’s the difference, really?

it was made specifically to circumvent all anti cheat checks.
and internally work more efficiently

**Comment by Mazedotexe** [comment]
> > > use the react gui instead 🗿
> > 
> > 
> > What’s the difference, really?
> 
> it was made specifically to circumvent all anti cheat checks. and internally work more efficiently

Well then first of all, why does the normal GUI show up first while the react one shows up last, and also, what anti cheat checks are there? How does it work more efficiently?

**Comment by 05Konz** [comment]
> > > > use the react gui instead 🗿
> > > 
> > > 
> > > What’s the difference, really?
> > 
> > 
> > it was made specifically to circumvent all anti cheat checks. and internally work more efficiently
> 
> Well then first of all, why does the normal GUI show up first while the react one shows up last, and also, what anti cheat checks are there? How does it work more efficiently?

cuz jod didn't know how well it would work in the gui's place so he left both of them on the repo, there are checks for class names and div elements with text that would only appear on the gui, it's made in react instead of spaghetti code

**Pull request closed without merging**
